server:
  port: 8083

spring:
  application:
    name: prediction-service

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3305/prediction_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:BarthaAlma2002}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health

services:
  user-service-url: ${USER_SERVICE_URL:http://localhost:8081}
  match-service-url: ${MATCH_SERVICE_URL:http://localhost:8082}